### ISSUE TITLE
update rhui3-automation to ansible 2.2

### ISSUE THREAD

**Issue by alexxa** [RedHatQE/rhui3-automation#11]
Using bare variables is deprecated. The update of playbooks is needed so that the environment 
value uses the full variable syntax.

**Comment by alexxa** [comment]
` [WARNING]: Consider using yum module rather than running yum` on task  [rhui_nodes: perform repolist](https://github.com/RedHatQE/rhui3-automation/blob/master/deploy/roles/rhui_nodes/tasks/main.yml#L34)

Fix: replace shell for yum module

**Comment by RadekBiba** [comment]
Already resolved. I'll create a separate issue for the replacement of shell with the yum module.
