### ISSUE TITLE
test naming

### ISSUE THREAD

**Issue by alexxa** [RedHatQE/rhui3-automation#129]
@RadekBiba Is there any way test naming can be changed? It's not cool to update numeration every time a new test added.

**Comment by RadekBiba** [comment]
Yeah, I agree it's uncool. Unfortunately, we're limited by the fact that nosetests runs `test_*` functions in alphabetical order and we use the numbers to enforce our ordering of execution.

I try to add new tests cases to the end whenever possible, so in many cases no renumbering is necessary, but if a new test works on top of what has been done before (e.g. an entitlement certificate was created in the previous test and now I newly want to examine the certificate in a specific way), then it makes more sense to add the new step somewhere between two existing tests, in which case the renumbering of the rest is inevitable. Well, sort of. You could put `test_06_1_xx` between` test_06_something` and `test_07_another_thing`, but that would look bad forever, whereas the renumbering is only annoying in the commit that introduced `test xx`.

I can also think of a scheme where the numbers are initially more sparse: we could have `test_01_login`, `test_10_add_cds`, `test_20_add_hap`, etc, and if we need to add something between the last two, we could add `test_15_something_new`. I'm less inclined to do this, though.

Any other ideas are welcome.

**Comment by RadekBiba** [comment]
And I might be wrong about `test_06_1` being executed after `test_06_something` - I guess `1` would go before `something` after all. I'd have to rename the latter to `test_06_01_something` first and continue with `test_06_02_xx`. And it would still look ugly.

**Comment by RadekBiba** [comment]
No good solution has been proposed since November 2018, closing.

One thing to consider, though: write a new `test_something.py` file whenever that makes more sense than adding test cases into an existing file.
