### ISSUE TITLE
libffi-devel and openssl-devel missing

### ISSUE THREAD

**Issue by vex21** [RedHatQE/rhui3-automation#15]
The ansible installation of test suite fails because a couple of -devel packages are missing. 

- libffi-devel
- openssl-devel

Having installed those two manually, I was able to complete the ansible run.

**Comment by alexxa** [comment]
@vex21 Please confirm that it's applicable to NFS setup only. I can't reproduce it if Gluster.

**Comment by alexxa** [comment]
QA note: check if applicable to RHEL7 NFS.

Error is on RHEL6.8 NFS confirmed

**Comment by alexxa** [comment]
Fixed in commit 5515c80
