### ISSUE TITLE
Limit queries to DNS server

### ISSUE THREAD

**Issue by vex21** [RedHatQE/rhui3-automation#19]
In the wake of a security incident reported by Amazon, we need to limit access to the DNS server to the machines that are part of the RHUI setup only. We can either modify [named.conf](https://github.com/RedHatQE/rhui3-automation/blob/master/deploy/roles/dns/templates/named.conf.j2#L18) file or work with security group rules, depends on what proves to be a better approach.

**Comment by vex21** [comment]
The [named.conf](https://github.com/RedHatQE/rhui3-automation/blob/master/deploy/roles/dns/templates/named.conf.j2#L18) Line 18 needs to be changed from the current:
allow-query { any ; };
to:
allow-query { IP_address; IP_address; IP_address; IP_address; IP_address; };

The above IP_addresses are the IPs of the machines which are part of the RHUI setup, i.e. RHUA, CDS1, CDS2, HAProxy1, client machine, etc.
allow-query Docs:
http://www.zytrax.com/books/dns/ch7/queries.html#allow-query

**Comment by alexxa** [comment]
Closed with PR #20
