### ISSUE TITLE
Switch to make yum update prior to installation

### ISSUE THREAD

**Issue by Skullman** [RedHatQE/rhui3-automation#3]
As customer will probably want to install RHUI on **fully updated OSes**, we should also test it on these configurations. Switch that will cause ansible to run "yum update -y" first is for situations where you actually want to skip this lengthy process (might take more than several minutes) in order to test something not relevant to versions of packages (eg. do development on install scripts themselves).

**Comment by alexxa** [comment]
Fixed by cedcc63
