### ISSUE TITLE
Make repo names as constants loaded from yaml file

### ISSUE THREAD

**Issue by alexxa** [RedHatQE/rhui3-automation#49]
It's not cool to update repo names used in tests every time we update the cert. Therefore, repo names can be stored in one yaml file and test cases can take them from there.

**Comment by RadekBiba** [comment]
@alexxa: This is already implemented, isn't it? We have the `tested_repos.yaml` file with repo names.

**Comment by alexxa** [comment]
@RadekBiba True.
