### ISSUE TITLE
RHUIManagerRepo.add_rh_repo_by_repo works for Yum repos only or which repo attributes to store in tested_repos.yaml

### ISSUE THREAD

**Issue by alexxa** [RedHatQE/rhui3-automation#59]
Line [1]  will cause an error if repo has any other type but 'Yum', e.g for  

 `Red Hat Enterprise Linux Atomic Host (Trees) from RHUI`
 `    -  6 : Red Hat Enterprise Linux Atomic Host (Trees) from RHUI (Version 7.3.3) (Atomic)`

One of possible solutions: update `RHUIManagerRepo.add_rh_repo_by_repo` so it will take `reponame` of a single repo as an argument, not a `repolist` of several repos, and add `repo_type` as another argument, with default value 'Yum', since that type is used the most. Mind to update all tests calling that function. 

Before fixing this issue, we need to define what repo attributes to store in `tested_repos.yaml` or how to store them.  Some `rhui-manager` functions need the full name (+version+type), e.g. add_by_repo, schedule_sync, others just a name without version or type. Therefore, functions are supposed to take_plane|concatenate|split|extract relevant repo attributes. 

To me, storing a full repo name (i.e. +version+type) looks the most reasonable right now. Just because, it requires the minimum actions/knowledge from a user, as well as from functions which may need only name+version or just a name.  However, this solution is not applicable to a _special_  atomic repo, which has a floating version by the moment.

[1] https://github.com/RedHatQE/rhui3-automation/blob/master/tests/rhui3_tests_lib/rhuimanager_repo.py#L123

**Comment by alexxa** [comment]
This fix will also close issues #49 and #58

**Comment by RadekBiba** [comment]
Resolved:

- the method has been modified to work with any kind of repo, not just Yum
- the kind of repo is stored in tested_repos.yaml
- there's a method to put together the repo name, version, and optionally the kind; the version can be stored or determined on the fly, which is the case with Atomic (though we don't sync the Atomic Trees repo as it's been unreliable, so this isn't really used at present)
