### ISSUE TITLE
Include username in stack ID

### ISSUE THREAD

**Issue by RadekBiba** [RedHatQE/rhui3-automation#66]
The stack ID is currently created this way:

`STACK_ID = "STACK" + ''.join(random.choice(string.ascii_lowercase) for x in range(10))`

Consequently, it's not clear from the cloudformation page in AWS who owns which stack. Or from a different perspective, I can't see which stacks are mine.

Please include the user name (the `ec2_name` variable) in the stack ID as well to provide direct ownership information.

**Comment by pbartiko** [comment]
Resolved with https://github.com/RedHatQE/rhui3-automation/pull/67 .
