### ISSUE TITLE
get major.minor RHEL version

### ISSUE THREAD

**Issue by RadekBiba** [RedHatQE/rhui3-automation#99]
I'd like `Util.get_rhua_version()` from `rhui3_tests_lib.util` to return a float representing the complete major.minor version of RHEL running on the RHUA node. At present, the method only returns an integer with the major version (6 or 7), but I'd appreciate the minor version, too (6.9, 7.5), so I could assess the environment more accurately.

I'll make sure that existing test cases don't break.

Any objections, @alexxa ?

**Comment by alexxa** [comment]
@RadekBiba can you elaborate what you mean with  "assess the environment more accurately"? And what if one wants to run those playbooks on 6.2 for example?

**Comment by RadekBiba** [comment]
Sure. My main use case is the update of subscription-manager, which only needs to be done on RHEL 7.5, as SM is broken in the compose and there's a fix for it in z-stream. Older releases (e.g. 7.4) don't need updating, and future releases (7.6) will contain the z-stream fix. So, if I could check whether I'm on 7.5, I could run the update only there and save time (possibly tens of seconds) elsewhere. There may be other special cases in the future. And in general, I think higher granularity is better.

This issue isn't about playbooks. `Util.get_rhua_version()` is only used in test cases. This change will only change the type returned by this method from int to float. It's easy enough for any test case to retype the output to int _if needed_, or use `>` or `<`. For example, to check if you're on RHEL 6 (and you don't care which minor version it is), use `int(version) == 6`, or `version < 7` (if you don't expect RHEL 5). (Or `math.floor(version) == 6`, if you want to look cool.)

**Comment by alexxa** [comment]
I see, thanks for the explanation. Do it! =)

**Comment by RadekBiba** [comment]
I'm going to have to reopen this issue and redo the code. It turns out that float can't be used because the method then returns 6.1 on RHEL 6.10.

I guess I'll use a dictionary with the major version and the minor version.
